In [48]:
import pandas as pd
orders_df=pd.read_csv("Day9_Orders.csv")
products_df=pd.read_csv("Day9_Products.csv")
customers_df=pd.read_csv("Day9_Customers.csv")

# Inspect the Datasets:
In this step, the first few rows of the Orders, Customers, and Products datasets are displayed to understand their structure and identify the related columns needed for merging.

In [49]:
orders_df.head(3)

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered

In [50]:
products_df.head(3)

  Product_ID         Product_Name     Category  Unit_Price     Brand
0       P001  Wireless Headphones  Electronics        1499  SoundMax
1       P002  Mechanical Keyboard  Electronics        2499    KeyPro
2       P003       Wireless Mouse  Electronics         899  TechGear

In [51]:
customers_df.head(3)

  Customer_ID Customer_Name      City Region Membership_Type
0        C001  Aarav Sharma  Srinagar  North         Premium
1        C002     Zoya Khan     Delhi  North         Regular
2        C003   Rohan Mehta    Mumbai   West         Premium

# Examine Dataset Structure:
The column names and data types of each dataset are examined to understand the available information and identify suitable keys for combining the datasets.

In [52]:
print("Order columns :")
print(orders_df.columns)

print("\nCustomer columns :")
print(customers_df.columns)

print("\nProduct columns :")
print(products_df.columns)

Order columns :
Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity',
       'Payment_Method', 'Order_Status'],
      dtype='str')

Customer columns :
Index(['Customer_ID', 'Customer_Name', 'City', 'Region', 'Membership_Type'], dtype='str')

Product columns :
Index(['Product_ID', 'Product_Name', 'Category', 'Unit_Price', 'Brand'], dtype='str')

# Demonstrate DataFrame Concatenation:
The Orders dataset is divided into two parts and combined again using concat() to demonstrate row-wise DataFrame concatenation.

In [53]:
orders_part1 = orders_df.iloc[:len(orders_df)//2]
orders_part2 = orders_df.iloc[len(orders_df)//2:]

orders_concat = pd.concat([orders_part1, orders_part2], ignore_index=True)

orders_concat.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

# Identify Relationships Between Datasets:
The datasets are related through common identifiers. The Orders dataset contains Customer ID and Product ID, which can be used to connect it with the Customers and Products datasets. A left merge will be used to retain all order records while adding the corresponding customer and product information.

In [54]:
order_customer=pd.merge(orders_df,customers_df,on="Customer_ID",how="left")

In [55]:
order_customer.head(3)

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular

In [56]:
final_merged=pd.merge(order_customer,products_df,on="Product_ID", how="left")

In [57]:
final_merged.head(3)

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech

# Create Total Price:
A new Total Price column is created using the Quantity and Unit Price columns. The apply() function is used to calculate the total price for each order.

In [60]:
def total_price(row):
    return row["Quantity"]*row["Unit_Price"]
final_merged["Total Price"]=final_merged.apply(total_price,axis=1)

In [61]:
final_merged.head(3)

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand,Total Price
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro,4998
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear,1798
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech,3299

# Process Order Date:
The Order Date column is converted to datetime format to enable date-based operations and extraction of useful information such as month, day, and day of the week.

In [62]:
final_merged["Order_Date"]=pd.to_datetime(final_merged["Order_Date"])

In [63]:
final_merged["Order Year"]=final_merged['Order_Date'].dt.year

In [64]:
final_merged["Order Month"]=final_merged['Order_Date'].dt.month

In [65]:
final_merged["Order Day"]=final_merged['Order_Date'].dt.day

In [66]:
final_merged["Order Day Of Week"]=final_merged['Order_Date'].dt.day_name()

In [68]:
final_merged.head(3)

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand,Total Price,Order Year,Order Month,Order Day,Order Day Of Week
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro,4998,2026,2,19,Thursday
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear,1798,2026,1,25,Sunday
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech,3299,2026,2,26,Thursday

# Organize the Final Dataset:
The processed dataset is organized into a clear and meaningful column order by grouping order, customer, product, and derived date information together.

In [71]:
final_merged = final_merged.loc[:, [
    "Order_ID", "Order_Date", "Customer_ID", "Product_ID",
    "Customer_Name", "City", "Region", "Membership_Type",
    "Product_Name", "Category", "Brand", "Unit_Price",
    "Quantity", "Total Price", "Payment_Method", "Order_Status",
    "Order Year", "Order Month", "Order Day", "Order Day Of Week"
]]

final_merged.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Brand,Unit_Price,Quantity,Total Price,Payment_Method,Order_Status,Order Year,Order Month,Order Day,Order Day Of Week
0,O0001,2026-02-19,C027,P019,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,BatPro,2499,2,4998,Credit Card,Delivered,2026,2,19,Thursday
1,O0002,2026-01-25,C006,P003,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,TechGear,899,2,1798,Debit Card,Delivered,2026,1,25,Sunday
2,O0003,2026-02-26,C015,P004,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,FitTech,3299,1,3299,Cash on Delivery,Delivered,2026,2,26,Thursday
3,O0004,2026-03-04,C024,P015,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,AIPress,999,3,2997,Net Banking,Delivered,2026,3,4,Wednesday
4,O0005,2026-03-29,C025,P009,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,HomeBrew,3499,5,17495,Credit Card,Delivered,2026,3,29,Sunday

# Export the Processed Dataset:
The final processed e-commerce dataset is exported as a CSV file for further use and submission.

In [72]:
final_merged.to_csv("processed_ecommerce_dataset.csv", index=False)

# Verify Exported Dataset:
The exported CSV file is loaded back into pandas to verify that the processed dataset was saved correctly.

In [73]:
verified_df = pd.read_csv("processed_ecommerce_dataset.csv")
verified_df.head(3)

,Order_ID,Order_Date,Customer_ID,Product_ID,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Brand,Unit_Price,Quantity,Total Price,Payment_Method,Order_Status,Order Year,Order Month,Order Day,Order Day Of Week
0,O0001,2026-02-19,C027,P019,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,BatPro,2499,2,4998,Credit Card,Delivered,2026,2,19,Thursday
1,O0002,2026-01-25,C006,P003,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,TechGear,899,2,1798,Debit Card,Delivered,2026,1,25,Sunday
2,O0003,2026-02-26,C015,P004,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,FitTech,3299,1,3299,Cash on Delivery,Delivered,2026,2,26,Thursday